{
    "name": "Custom Billing Report",
    "version": "18.0.1.2.0",
    "category": "Accounting/Reporting",
    "summary": (
        "Detailed billing reports with interactive dashboard, "
        "PDF and Excel export."
    ),
    "author": "lfernandez",
    "website": "https://github.com/luisferllub230/custom_billing_report",
    "license": "LGPL-3",
    "depends": [
        "account",
        "web",
        "l10n_latam_invoice_document",
    ],
    "data": [
        "security/ir.model.access.csv",
        "wizard/billing_report_wizard_views.xml",
        "views/billing_dashboard_views.xml",
        "views/billing_report_menus.xml",
        "report/billing_report_actions.xml",
        "report/billing_report_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "custom_billing_report/static/src/scss/billing_dashboard.scss",
            "custom_billing_report/static/src/js/billing_trend_chart.js",
            "custom_billing_report/static/src/js/billing_health_gauge.js",
            "custom_billing_report/static/src/js/billing_paid_pie_chart.js",
            "custom_billing_report/static/src/js/billing_top_customers_chart.js",
            "custom_billing_report/static/src/js/billing_top_salespersons_chart.js",
            "custom_billing_report/static/src/js/billing_top_creators_chart.js",
            "custom_billing_report/static/src/js/billing_payment_category_chart.js",
            "custom_billing_report/static/src/js/billing_payment_comparative_chart.js",
            "custom_billing_report/static/src/js/billing_dashboard.js",
            "custom_billing_report/static/src/xml/billing_trend_chart.xml",
            "custom_billing_report/static/src/xml/billing_health_gauge.xml",
            "custom_billing_report/static/src/xml/billing_paid_pie_chart.xml",
            "custom_billing_report/static/src/xml/billing_top_customers_chart.xml",
            "custom_billing_report/static/src/xml/billing_top_salespersons_chart.xml",
            "custom_billing_report/static/src/xml/billing_top_creators_chart.xml",
            "custom_billing_report/static/src/xml/billing_payment_category_chart.xml",
            "custom_billing_report/static/src/xml/billing_payment_comparative_chart.xml",
            "custom_billing_report/static/src/xml/billing_dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
